### ISSUE TITLE
Implement storage to store Raft logs using RocksDB

### ISSUE THREAD

**Issue by mosuka** [mosuka/bayard#11]
Implement storage to store Raft logs using RocksDB.

**Comment by winwisely99** [comment]
How does it do Raft now ?

**Comment by mosuka** [comment]
Hi @winwisely99 ,
The storage is to store Raft logs. Right now I use `MemStorage`, but I want to implement it using RocksDB so that instance can keep the previous transaction logs even if it restarts.
However, I have not enough time to implement it now, so it has not been implemented yet.

**Comment by winwisely99** [comment]
OK thanks @mosuka 

RocksDB sounds good !!

Did you see that are replacing it with a 100% golang implementation of rocks DB over at the CockRoach repo ?

https://github.com/cockroachdb/pebble

And dragonboat uses it now 
https://github.com/lni/dragonboat

https://github.com/lni/dragonboat/blob/master/docs/storage.md

---

If your only using rust then you cant really use dragonboat, etc
But if you get the Rust code to use the dragonboat and pebble in a different server then you could use it. 

Curious what you think as you have so much experience in this area from Cete and Blast.

We are running dragonboat as an experiment at the moment.
