### ISSUE TITLE
Consistency guarantees

### ISSUE THREAD

**Issue by jfinity** [mosuka/bayard#116]
Bayard looks great!  I'm interested in transactional full-text search.

What can happen in a concurrent scenario like the following?

| client1                     | client2                     |
|-----------------------------|-----------------------------|
| A) bulk-set [{id:1},{id:2}] | X) bulk-set [{id:5},{id:6}] |
| B) bulk-set [{id:3},{id:4}] | Y) bulk-set [{id:3},{id:4}] |
| C) commit                   | Z) rollback                 |

Among other things:
1. Can client1 commit documents `5` and `6` if  `C` "happens before" `Z` but "happens after" `X`?
2. Do documents in `Y` overrule documents in `B` if `C` "happens before" `Z` but "happens after" `Y`?
3. If client1 and client2 are talking to different bayard nodes, is the behavior different than talking to the same bayard node?
4. Are client transactions isolated from each other even if they are talking to the same bayard node?

**Comment by mosuka** [comment]
Hi @jfinity ,

> Can client1 commit documents 5 and 6 if C "happens before" Z but "happens after" X?

Yes.

> Do documents in Y overrule documents in B if C "happens before" Z but "happens after" Y?

Yes.

> If client1 and client2 are talking to different bayard nodes, is the behavior different than talking to the same bayard node?

Bayard can bring up a cluster with at least 3 or more odd nodes. A cluster consists of one leader and multiple followers. Only the leader is allowed to accept update requests in the cluster, and if a follower accepts an update request, it returns an error. Search requests can be accepted by any node.
However, if you are using `bayard-cli`, if you make an update request to a follower and get an error, it can still detect the leader and resend it to the leader.

> Are client transactions isolated from each other even if they are talking to the same bayard node?

Bayard does not have robust transaction management capabilities. The update requests accepted by the leader node are processed in sequence.
