### ISSUE TITLE
Monotonic updates

### ISSUE THREAD

**Issue by jfinity** [mosuka/bayard#117]
I wish I could have a [changefeed from cockroachdb](https://www.cockroachlabs.com/docs/stable/changefeed-for.html) populate a search index in an idempotent way using the [`updated` timestamp](https://www.cockroachlabs.com/docs/stable/changefeed-for.html#options) for automatic merge resolution of documents with the same id.

Would you be willing to add a feature like [external document versioning (from elasticsearch...)](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning)?

Edit 1:  So if document with id 1 exists in the index with version 5, any set/bulk-set with document id 1 at version 5 or less is ignored, but version 6 and above replace the indexed value.

**Comment by mosuka** [comment]
Hi @jfinity ,
Thanks for your suggestion.
Bayard still has other issues to do, so I'll consider it when I make the time. :)

**Comment by jfinity** [comment]
In case it still interests you, I thought some more about monotonic updates (while looking at typesense..).

Rather than monotonic versioning(/conflict-resolution) at the document-level, monotonic thresholding at the index-level (or cluster-level) could alleviate the need for tombstone preservation in the service and/or lease management in the client.
