### ISSUE TITLE
Bulk search API

### ISSUE THREAD

**Issue by rhanka** [mosuka/bayard#123]
Hi, we're currently using elasticsearch for https://deces.machid.io (using powerful levensthein fuzzy search).

We use bulk search to record linkage usecase (usefull for clinic studies). 
We would be enthousiastic to study the port from elastiscearch to bayard, but bayard is missing this key feature.

Do you plan to have such bulk search api ?

**Comment by mosuka** [comment]
Hi @rhanka ,
Sorry for the late reply.
Thanks for your interest in this project!
There are no plans to implement a bulk search API at the moment.
I would like to implement it when I get time, but I can't promise when I will be able to.

**Comment by barrotsteindev** [comment]
@rhanka , do you mean [multi search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html)?

**Comment by rhanka** [comment]
Yes that is multi search i.e send one big json with multiple requests
inside.
On elaticsearch it most of requests 10x faster requests reducing http API
useless overload.
Search isnt made for join like SQL but this is often usefull.

Bulk is even more usefull at indexing time too but i guess it is already
implemented.

Le lun. 8 févr. 2021 à 15:41, barrotsteindev <notifications@github.com> a
écrit :
