### ISSUE TITLE
ドキュメントのRequirements記述が不足している

### ISSUE THREAD

**Issue by osakanataro** [mosuka/bayard#130]
Ubuntu 20.04環境にてbayardを動かそうと sudo apt install rustc を実行したあと
https://bayard-search.github.io/bayard/install.html に従い「cargo install bayard」を実行したところ、パッケージが足りずに失敗しました。
最終的には 「sudo apt install librust-openssl-dev cmake golang」を行うことでセットアップが完了しました。

**Comment by mosuka** [comment]
ご報告ありがとうございます。
後で修正しておきます。
