### ISSUE TITLE
unwrap() causing errors 

### ISSUE THREAD

**Issue by jimmy980189** [mosuka/bayard#131]
Hi there, currently I'm trying to use `Bayard` as index server for my side project.
But I've tried many times when `Bayard` encountered illegal query (eq: `A - B`)
It will stop and never reply for any queries, so that I have to restart the server to make things works again.
(I followed the instructions in documentation to build a 3-nodes `Bayard` cluster.)

![image](https://user-images.githubusercontent.com/45072996/125404489-3f129680-e3e9-11eb-89ea-8ddee3a45a67.png)
I traced the source code and found out that maybe it was caused by these lines in `bayard-server/src/index/server.rs`

![image](https://user-images.githubusercontent.com/45072996/125405940-da583b80-e3ea-11eb-8551-7013c9a547d6.png)

![image](https://user-images.githubusercontent.com/45072996/125405850-c0b6f400-e3ea-11eb-8b89-2cdc3fac3c3e.png)

![image](https://user-images.githubusercontent.com/45072996/125405904-cf9da680-e3ea-11eb-9cc5-1dd8aec34b2c.png)

I've tried to modified these two `unwap()` to other Rust error handling methods (eg: `match .... { Ok() => ... , Err() => ... }` .
But it seems that the sender is still stuck in middle. (I've checked the requests was normally sent into the server by changing the `debug!` to `println!`  in
![image](https://user-images.githubusercontent.com/45072996/125406935-f7d9d500-e3eb-11eb-98f9-739d8c4a251f.png)
) 

Hope to have a solution here, thanks or I'll have to create a filter to prevent illegal queries.
`Bayard` perfectly fits my needs except for supporting multiple indexes 😭

**Comment by mosuka** [comment]
Hi @jimmy980189,
Sorry for the late reply and thank you for your comment.
I'll refactor the code.
